# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64" # 16.04
  config.vm.provision :shell, path: "../../boss",
                      args: "install test.local first phpinfo phpmyadmin cert lamp composer craft3 newuser xdebug netdata bashrc -Ndbname -Ppassword -usm,password -csm,sm@8cylinder.com,password"
  config.vm.synced_folder "../../", "/project"
end

