# Enable verbose debugging
debug: true
verbose: true

# Configure logging
output: {all: '| tee -a /var/log/cloud-init-output.log'}

packages:
  - pipx

#mounts:
#  - [ /home/sm/projects/boss, /home/ubuntu/boss ]

runcmd:
  - snap install astral-uv --classic
  - pipx install /home/ubuntu/dist/boss*.whl

users:
  - default
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDmubzMqHo0efxcgNFlkKGaQkK17hriHnffsGhuXjl9K sheldon@8cylinder.com
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOXJgF6vwElABsqWzKBdOOMn/MGzSAUq6mlxYcNP6Zjy sheldon@8cylinder.com
  - name: sm
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDmubzMqHo0efxcgNFlkKGaQkK17hriHnffsGhuXjl9K sheldon@8cylinder.com
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOXJgF6vwElABsqWzKBdOOMn/MGzSAUq6mlxYcNP6Zjy sheldon@8cylinder.com
