# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64" # 16.04
  # config.vm.provision :shell, path: "../../boss",
  #                     args: "install test.local phpinfo phpmyadmin cert -Ndbname -Ppassword -usm,password -csm,sm@8cylinder.com,password",
  #                     keep_color: true,
  #                     privileged: false
  config.vm.synced_folder "../../", "/project"
end
