# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64" # 16.04
  config.vm.provision :shell, path: "../../boss/boss",
                      args: "install test.local first phpinfo phpmyadmin cert lamp composer craft3 newuser xdebug -Ndbname -Ppassword -usm,password -csm,sm@8cylinder.com,password"
  config.vm.synced_folder "../../boss", "/project"


end
