# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64" # 16.04
  config.vm.provision :shell, path: "../../boss",
                      args: "install test8.local phpmyadmin phpinfo cert composer lamp virtualhost craft3 fakesmtp xdebug -stest8.local,/var/www/public_html,y -Ntest8 -csm,sheldon@8cylinder.com,password",
                      keep_color: true,
                      privileged: false
  config.vm.synced_folder "../../", "/project"

  config.vm.define "test8" do |test8| end
  config.vm.network "private_network", ip: "192.168.56.199"
  config.vm.hostname = "test8.local"

  config.vm.provider :virtualbox do |vb|
    # https://stackoverflow.com/q/28323953/2177602
    # https://stackoverflow.com/a/18457420/2177602
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    # vb.cpus = 4
    vb.memory = 8192 # default 1024
  end
end
